apiVersion: v1
kind: Secret
metadata:
  name: infisical-kubernetes-auth
  namespace: infisical-auth
type: Opaque
stringData:
  identityId: "ID of the machine identite used for external secrets operator"
