# proxmox-csi.yaml
config:
  clusters:
    - url: https://x.x.x.x:8006/api/json
      insecure: true
      token_id: "kubernetes-csi@pve!csi"
      # The token secret should be present in your terraform state if you used terraform to provision the resources
      token_secret: ""
      # Proxmox cluster name, find it in the webui > Datacenter > Cluster > Cluster-Information
      region: ""

# Define the storage classes
storageClass:
  - name: proxmox-data-xfs
    storage: data
    reclaimPolicy: Delete
    fstype: xfs
    ssd: true 
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"

node:
  # This key is not required if using kubespray/kubeadm
  kubeletDir: /var/lib/k0s/kubelet