apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: proxmox-csi-plugin-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        config.yaml: |
          clusters:
            - url: https://192.168.1.100:8006/api2/json
              insecure: true
              token_id: "kubernetes-csi@pve!csi"
              token_secret: "{{ .tokenSecret }}"
              region: "Proxmox-Cluster"
  data:
    - secretKey: tokenSecret
      remoteRef:
        key: proxmox_csi_token
