apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-mini
  user: miniadmin
spec:
  hosts:
  - role: controller
    ssh:
      address: ${CONTROLLER_IP}
      user: ${SSH_USER}
      keyPath: ${SSH_KEY}
    # k0s reads manifests directory in alphabetical order
    files:
      - name: metallb-installation
        src: https://raw.githubusercontent.com/metallb/metallb/v0.15.3/config/manifests/metallb-native.yaml
        dstDir: /var/lib/k0s/manifests/metallb/01-install.yaml
        perm: 0600
      - name: metallb-configuration
        src: ./metallb/metallb-config.yaml
        dstDir: /var/lib/k0s/manifests/metallb/02-config.yaml
        perm: 0600
   # bash-like expressions are supported in the configuration for environment variable substition
  - role: worker
    ssh:
      address: ${WORKER1_IP}
      user: ${SSH_USER}
      keyPath: ${SSH_KEY}
  - role: worker
    ssh:
      address: ${WORKER2_IP}
      user: ${SSH_USER}
      keyPath: ${SSH_KEY}
  - role: worker
    ssh:
      address: ${WORKER3_IP}
      user: ${SSH_USER}
      keyPath: ${SSH_KEY}
  k0s:
    version: v1.34.2+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: mini-k0s
      spec:
        network:
          provider: calico
        extensions: 
          helm: 
            repositories:
            - name: argo
              url: https://argoproj.github.io/argo-helm
            charts:
            - name: argo-cd
              chartname: argo/argo-cd
              version: "9.1.5"
              namespace: argocd
              order: 0
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m
      timeout: 5m
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true