apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametric-k8s-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.77.0
      helm:
        releaseName: vm-stack
        valueFiles:
          - $values/platform/victoriametrics-k8s-stack/victoriametrics-k8s-stack-values.yaml
    - repoURL: https://github.com/Equinox42/minilab
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
