global:
  domain: argocd.40cat-not-found.tech

crds:
  keep: false

redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

configs:
  params:
    server.insecure: true

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "cloudflare" 
      traefik.ingress.kubernetes.io/router.tls: "true"
    tls:
      - hosts:
          - argocd.40cat-not-found.tech
        secretName: argocd-tls-secret
